server:
  port: 8081
spring:
  #关闭thymeleaf缓存
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    name: testmywarehouse
#    url: jdbc:mysql://www.eastebiz.com:3306/testmywarehouse?useSSL=false&allowPublicKeyRetrieval=true
#    username: tozhr
#    password: 1234567oO#
    url: jdbc:mysql://123.207.2.212:3306/testmywarehouse?useSSL=false
    username: root
    password: 695027077123abc***...
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    allowPublicKeyRetrieval: true
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 123.207.2.212
    port: 6379
    password: 695027077123abc***
    timeout: 2S
    jedis:
      pool:
        max-idle: 8 #连接池中的最大空闲连接
        min-idle: 0
        #max-wait: -1S  #连接池最大阻塞等待时间（使用负值表示没有限制）

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.ebiz.model  # 注意：对应实体类的路径
  configuration:
    use-generated-keys: true #自动使用自增主键填充bean
    map-underscore-to-camel-case: true #开启驼峰命名
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
MAX_TIME_OUT: 5000

# druid数据源监控配置
durid:
  login:
    username: admin
    password: admin123